work_dir: './work_dir/prediction'
weights: './work_dir/prediction/fusion_2/adam_1e-4/lamda_06/cross_03/ablation-+vel+acc/iter40000_model.pt'
train_dir: '../data/cmu/train'
test_dir: '../data/cmu/test'

actions: 'all'
batch_size: 32
source_seq_len: 50
target_seq_len: 10

masking_type: lower-body
model: net.model.Model
model_args:
  n_in_enc: 3
  n_hid_enc: 256
  n_in_dec: 9
  n_hid_dec: 256
  fusion_layer: 2
  cross_w: 0.3
  graph_args_j:
    layout: 'cmu'
    strategy: 'distance'
  graph_args_p:
    layout: 'cmu'
    strategy: 'distance'
  graph_args_b:
    layout: 'cmu'
    strategy: 'distance'
edge_weighting: True
lamda: 0.6
 
phase: test
device: [0]
use_gpu: True

save_motion: True
fusion_layer_dir: test
learning_rate_dir: test
lamda_dir: test
crossw_dir: test
note: ablation-+vel+acc